import { createHash } from 'node:crypto'
import { mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import process from 'node:process'
import protobuf from 'protobufjs'

const root = resolve(import.meta.dirname, '../..')
const upstreamDeclaration = resolve(root, 'node_modules/baileys/WAProto/index.d.ts')
const upstreamSchema = resolve(root, 'node_modules/baileys/WAProto/WAProto.proto')
const upstreamPackage = resolve(root, 'node_modules/baileys/package.json')
const sourceTarget = resolve(root, 'src/WAProto/index.d.ts')
const schemaTarget = resolve(root, 'src/WAProto/compatibility-schema.ts')
const buildTarget = resolve(root, 'lib/WAProto/runtime.d.ts')

const generatedHeader = `// Generated by scripts/compatibility/waproto-facade.mjs. Do not edit.\n// Type-only Baileys compatibility facade; runtime codecs remain whatsapp-rust-bridge.\n`

const generatedContents = () => {
	const upstreamContents = readFileSync(upstreamDeclaration, 'utf8').replace(/\r\n/g, '\n')
	return `${generatedHeader}${upstreamContents}`
}

const FIELD_KIND = Object.freeze({
	message: 0,
	enum: 1,
	string: 2,
	bool: 3,
	bytes: 4,
	float: 5,
	signed32: 6,
	unsigned32: 7,
	signed64: 8,
	unsigned64: 9
})

const FIELD_FLAG = Object.freeze({
	repeated: 1,
	map: 2,
	proto3Optional: 4,
	oneof: 8
})

const scalarKind = type => {
	switch (type) {
		case 'string':
			return FIELD_KIND.string
		case 'bool':
			return FIELD_KIND.bool
		case 'bytes':
			return FIELD_KIND.bytes
		case 'float':
		case 'double':
			return FIELD_KIND.float
		case 'int32':
		case 'sint32':
		case 'sfixed32':
			return FIELD_KIND.signed32
		case 'uint32':
		case 'fixed32':
			return FIELD_KIND.unsigned32
		case 'int64':
		case 'sint64':
		case 'sfixed64':
			return FIELD_KIND.signed64
		case 'uint64':
		case 'fixed64':
			return FIELD_KIND.unsigned64
		default:
			throw new Error(`Unsupported protobuf scalar: ${type}`)
	}
}

const schemaPath = value => value.fullName.replace(/^\.proto\./, '')

const collectSchemaObjects = namespace => {
	const messages = []
	const enums = []
	const visit = current => {
		for (const value of Object.values(current.nested ?? {})) {
			if (value instanceof protobuf.Type) {
				messages.push(value)
				visit(value)
			} else if (value instanceof protobuf.Enum) {
				enums.push(value)
			} else if (value instanceof protobuf.Namespace) {
				visit(value)
			}
		}
	}
	visit(namespace)
	messages.sort((left, right) => schemaPath(left).localeCompare(schemaPath(right)))
	enums.sort((left, right) => schemaPath(left).localeCompare(schemaPath(right)))
	return { messages, enums }
}

const generatedSchemaContents = () => {
	const loaded = protobuf.loadSync(upstreamSchema)
	loaded.resolveAll()
	const namespace = loaded.lookup('proto')
	if (!(namespace instanceof protobuf.Namespace)) {
		throw new Error('The pinned WAProto schema does not expose the expected proto namespace')
	}

	const { messages, enums } = collectSchemaObjects(namespace)
	const messageIds = new Map(messages.map((message, index) => [message.fullName, index]))
	const enumIds = new Map(enums.map((enumType, index) => [enumType.fullName, index]))
	const messageSchemas = messages.map(message => [
		schemaPath(message),
		message.fieldsArray.map(field => {
			const isProto3Optional = field.options?.proto3_optional === true
			const flags =
				(field.repeated ? FIELD_FLAG.repeated : 0) |
				(field.map ? FIELD_FLAG.map : 0) |
				(isProto3Optional ? FIELD_FLAG.proto3Optional : 0) |
				(field.partOf && !isProto3Optional ? FIELD_FLAG.oneof : 0)
			let kind
			let reference = -1
			if (field.resolvedType instanceof protobuf.Type) {
				kind = FIELD_KIND.message
				reference = messageIds.get(field.resolvedType.fullName)
			} else if (field.resolvedType instanceof protobuf.Enum) {
				kind = FIELD_KIND.enum
				reference = enumIds.get(field.resolvedType.fullName)
			} else {
				kind = scalarKind(field.type)
			}
			if (reference === undefined) {
				throw new Error(`Unresolved schema reference: ${message.fullName}.${field.name}`)
			}
			return [field.name, kind, reference, flags, flags & FIELD_FLAG.oneof ? field.partOf.name : '']
		})
	])
	const enumSchemas = enums.map(enumType => [schemaPath(enumType), Object.entries(enumType.values).flat()])
	const packageMetadata = JSON.parse(readFileSync(upstreamPackage, 'utf8'))
	const schemaBytes = readFileSync(upstreamSchema)
	const schemaHash = createHash('sha256').update(schemaBytes).digest('hex')
	const source = `${packageMetadata.name}@${packageMetadata.version}:${schemaHash}`

	return (
		`// Generated by scripts/compatibility/waproto-facade.mjs. Do not edit.\n` +
		`// Compact conversion metadata only; this file contains no protobuf codec.\n` +
		`export type ProtoFieldSchema = readonly [name: string, kind: number, reference: number, flags: number, oneof: string]\n` +
		`export type ProtoMessageSchema = readonly [path: string, fields: readonly ProtoFieldSchema[]]\n` +
		`export type ProtoEnumSchema = readonly [path: string, entries: readonly (string | number)[]]\n` +
		`export const PROTO_FIELD_KIND = ${JSON.stringify(FIELD_KIND)} as const\n` +
		`export const PROTO_FIELD_FLAG = ${JSON.stringify(FIELD_FLAG)} as const\n` +
		`export const PROTO_SCHEMA_SOURCE = ${JSON.stringify(source)}\n` +
		`export const PROTO_MESSAGE_SCHEMAS = ${JSON.stringify(messageSchemas)} as readonly ProtoMessageSchema[]\n` +
		`export const PROTO_ENUM_SCHEMAS = ${JSON.stringify(enumSchemas)} as readonly ProtoEnumSchema[]\n`
	)
}

const write = (target, contents) => {
	mkdirSync(dirname(target), { recursive: true })
	writeFileSync(target, contents)
}

const mode = process.argv[2] ?? '--sync'
const contents = generatedContents()
const schemaContents = generatedSchemaContents()

if (mode === '--check') {
	let currentDeclaration
	let currentSchema
	try {
		currentDeclaration = readFileSync(sourceTarget, 'utf8')
	} catch {
		currentDeclaration = undefined
	}
	try {
		currentSchema = readFileSync(schemaTarget, 'utf8')
	} catch {
		currentSchema = undefined
	}
	if (currentDeclaration !== contents || currentSchema !== schemaContents) {
		process.stderr.write('WAProto compatibility facade is stale; run npm run compat:sync-waproto\n')
		process.exitCode = 1
	}
} else if (mode === '--copy-build') {
	write(buildTarget, contents)
	rmSync(`${buildTarget}.map`, { force: true })
} else if (mode === '--sync') {
	write(sourceTarget, contents)
	write(schemaTarget, schemaContents)
} else {
	throw new Error(`Unknown mode: ${mode}`)
}
